### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by jedjebari** [cloudfoundry/java-buildpack-client-certificate-mapper#1]
Hi

Is there a way to debug what's happening ?
I tried to use the mapper feature but still have an exception with restTemplate.

Can you confirm I have to activate the mapper with `JBP_CONFIG_CONTAINER_CERTIFICATE_TRUST_STORE` ?

Edit : I'm using the java buildpack #4.3, and the mapper is well loaded :
```
-----> Downloading Client Certificate Mapper 1.1.0_RELEASE from https://java-buildpack.cloudfoundry.org/client-certificate-mapper/client-certificate-mapper-1.1.0_RELEASE.jar (found in cache)
```

Thanks
Jerome

**Comment by nebhale** [comment]
Note the configuration you've listed is `CONTAINER_CERTIFICATE_TRUST_STORE` which is not the Client Certificate Mapper.  The Client Certificate Trust Store has been [replaced](https://github.com/cloudfoundry/java-buildpack/releases/tag/v4.1) by the [Container Security Provider](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-container_security_provider.md).
