### ISSUE TITLE
Make Headername Configurable

### ISSUE THREAD

**Issue by patsys** [cloudfoundry/java-buildpack-client-certificate-mapper#3]
This is a feature request because the XFCC header is not a standart and it does not exist a standart please make the header field name Configurable over an Environment Variable with default on XFCC.

**Comment by nebhale** [comment]
It's not a standard, but it is a de facto standard.  The two entry points to applications in Cloud Foundry, `gorouter` and Envoy both use this header (although the payloads are different).  As this project is oriented explicitly towards CF, that would seem to cover all ingress points.
