### ISSUE TITLE
Not compatible with Spring Boot 3

### ISSUE THREAD

**Issue by martinvisser** [cloudfoundry/java-buildpack-client-certificate-mapper#7]
The current solution is based on Spring Boot 2.6, which works well with Spring Boot 2.7 as well, but no longer with Spring Boot 3. The autoconfiguration isn't loaded, partially because it uses `spring.factories` and partially because it check for `javax` packages. Spring Boot 3 has been upgraded to use the Jakarta namespace.

**Comment by pivotal-david-osullivan** [comment]
Closed via v2.0.1
